version: '2.3'
services:
  
  db:
    image: gs/db
    volumes:
      - ./database_volume:/var/lib/postgresql/data
    #user: ${CURRENT_UID}
    
  web:
    image: gs/base_rails    
    depends_on:
      - db
    volumes:
      - ./workspace_volume:/usr/local/workspace/
    working_dir: /usr/local/workspace/ 
    
    command: bash entry.sh 
    
    ports:
      - "3000:3000"



